name: Reserve Return Ticket
on: 
  schedule:
    - cron: '42 23 * * MON'  # Every Monday at 09:00 UTC (MIN HOUR DAY MONTH DAYOFWEEK)
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select the environment
        required: true
        options:
          - Trip for 1
          - Trip for 2
jobs:
  reserve-ticket:
    runs-on: ubuntu-24.04
    environment: ${{ github.event.inputs.environment || 'Trip for 1'}}
    env:
      LOG_LEVEL: ${{ vars.LOG_LEVEL }}
      LOGIN: ${{ vars.LOGIN }}
      SLOW_MO: ${{ vars.SLOW_MO }}
      HEADLESS: ${{ vars.HEADLESS }}
      EMAIL: ${{ vars.EMAIL }}
      PASSWORD: ${{ secrets.PASSWORD }}
      ORIGIN: ${{ vars.DESTINATION }}
      DESTINATION: ${{ vars.ORIGIN }}
      DEPARTURE_DATE: ${{ vars.DEPARTURE_DATE_RETURN }}
      DEPARTURE_TIME: ${{ vars.DEPARTURE_TIME_RETURN }}
      IDS: ${{ secrets.IDS }}
      NAMES: ${{ vars.NAMES }}
      RAIL_GREEN_PASSES: ${{ secrets.RAIL_GREEN_PASSES }}
    steps:
      - name: Download docker
        run: |
          docker pull ghcr.io/jmsmarques/cp_concierge:latest
      - name: Wait until departure time
        run: |
          while true; do
          now=$(date -u +"%H:%M")
          if [ "$now" \> "$DEPARTURE_TIME" ] || [ "$now" = "$DEPARTURE_TIME" ]; then
            echo "It's time to proceed."
            break
          else
            echo "Current time ($now) is before departure time ($DEPARTURE_TIME). Sleeping for 30 seconds..."
            sleep 30
          fi
            done
      - name: Reserve Return Ticket
        run: |
          docker run --rm \
          -e LOG_LEVEL="DEBUG" \
          -e DRY_RUN="$DRY_RUN" \
          -e LOGIN="$LOGIN" \
          -e SLOW_MO="$SLOW_MO" \
          -e HEADLESS="$HEADLESS" \
          -e EMAIL="$EMAIL" \
          -e PASSWORD="$PASSWORD" \
          -e ORIGIN="$ORIGIN" \
          -e DESTINATION="$DESTINATION" \
          -e DEPARTURE_DATE="$DEPARTURE_DATE" \
          -e DEPARTURE_TIME="$DEPARTURE_TIME" \
          -e IDS="$IDS" \
          -e NAMES="$NAMES" \
          -e RAIL_GREEN_PASSES="$RAIL_GREEN_PASSES" \
          ghcr.io/jmsmarques/cp_concierge:latest
