name: reserve-ticket
on: 
  workflow_dispatch:
jobs:
  reserve-ticket:
    runs-on: ubuntu-24.04
    env:
      LOGIN: ${{ vars.LOGIN }}
      SLOW_MO: ${{ vars.SLOW_MO }}
      HEADLESS: ${{ vars.HEADLESS }}
      EMAIL: ${{ vars.EMAIL }}
      PASSWORD: ${{ secrets.PASSWORD }}
      NR_PASSENGERS: ${{ vars.NR_PASSENGERS }}
      ORIGIN: ${{ vars.ORIGIN }}
      DESTINATION: ${{ vars.DESTINATION }}
      DEPARTURE_DATE: ${{ vars.DEPARTURE_DATE }}
      DEPARTURE_TIME: ${{ vars.DEPARTURE_TIME }}
      IDS: ${{ secrets.IDS }}
      NAMES: ${{ vars.NAMES }}
      RAIL_GREEN_PASSES: ${{ secrets.RAIL_GREEN_PASSES }}
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Playwright Chromium
        run: python -m playwright install --with-deps chromium
      - name: Run script
        run: python main.py
