name: reserve-ticket
on: 
  workflow_dispatch:
jobs:
  reserve-ticket:
    runs-on: ubuntu-24.04
    env:
      LOGIN: ${{ vars.LOGIN }}
      SLOW_MO: ${{ vars.SLOW_MO }}
      HEADLESS: ${{ vars.HEADLESS }}
      EMAIL: ${{ vars.EMAIL }}
      PASSWORD: ${{ secrets.PASSWORD }}
      NR_PASSENGERS: ${{ vars.NR_PASSENGERS }}
      ORIGIN: ${{ vars.ORIGIN }}
      DESTINATION: ${{ vars.DESTINATION }}
      DEPARTURE_DATE: ${{ vars.DEPARTURE_DATE }}
      DEPARTURE_TIME: ${{ vars.DEPARTURE_TIME }}
      IDS: ${{ secrets.IDS }}
      NAMES: ${{ vars.NAMES }}
      RAIL_GREEN_PASSES: ${{ secrets.RAIL_GREEN_PASSES }}
    steps:
      - name: Download docker
        run: |
          docker pull ghcr.io/jmsmarques/cp_concierge:latest
      - name: Run container
        run: |
          docker run --rm -e DRY_RUN=$DRY_RUN \
            -e LOGIN=$LOGIN -e SLOW_MO=$SLOW_MO \
            -e HEADLESS=$HEADLESS -e EMAIL=$EMAIL \
            -e PASSWORD=$PASSWORD -e ORIGIN=$ORIGIN \
            -e DESTINATION=$DESTINATION -e DEPARTURE_DATE=$DEPARTURE_DATE \
            -e DEPARTURE_TIME=$DEPARTURE_TIME -e IDS=$ID -e NAMES=$NAMES \
            -e RAIL_GREEN_PASSES=$RAIL_GREEN_PASSES \
            cp_concierge:latest